// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportConnect.Models;

#nullable disable

namespace SportConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123141802_NotificacaoController")]
    partial class NotificacaoController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CriarGrupo.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ListaEspera")
                        .HasColumnType("bit");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroMaximoParticipantes")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SportConnect.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("GrupoId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("SportConnect.Models.Modalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Futebol"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vôlei"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Futsal"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Basquete"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Natação"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Caminhada e Corrida"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Ciclismo"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Tênis de Mesa"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Musculação"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Surf"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Skate"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Judô"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Jiu-Jitsu"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Boxe"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Capoeira"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Handebol"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Vôlei de Praia"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Futevôlei"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Tênis"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Atletismo"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Ginástica Artística"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Ginástica Rítmica"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Taekwondo"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Karatê"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Mountain Bike"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Canoagem"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Remo"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Polo Aquático"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Halterofilismo"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Golfe"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Beisebol"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Softbol"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Futebol Americano"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Rugby"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Esgrima"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Tiro Esportivo"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Hipismo"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Badminton"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Squash"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Peteca"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "Beach Tennis"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Padel"
                        },
                        new
                        {
                            Id = 43,
                            Nome = "Pesca Esportiva"
                        },
                        new
                        {
                            Id = 44,
                            Nome = "Triatlo"
                        },
                        new
                        {
                            Id = 45,
                            Nome = "Muay Thai"
                        },
                        new
                        {
                            Id = 46,
                            Nome = "Iatismo/Vela"
                        },
                        new
                        {
                            Id = 47,
                            Nome = "Automobilismo"
                        },
                        new
                        {
                            Id = 48,
                            Nome = "Motociclismo"
                        },
                        new
                        {
                            Id = 49,
                            Nome = "Dança Esportiva"
                        },
                        new
                        {
                            Id = 50,
                            Nome = "Xadrez"
                        });
                });

            modelBuilder.Entity("SportConnect.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataEnvio")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Lida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("SportConnect.Models.Participacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataInscricao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusParticipacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Participacoes");
                });

            modelBuilder.Entity("SportConnect.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CriarGrupo.Models.Grupo", b =>
                {
                    b.HasOne("SportConnect.Models.Usuario", "Usuario")
                        .WithMany("Grupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportConnect.Models.Evento", b =>
                {
                    b.HasOne("SportConnect.Models.Usuario", "Criador")
                        .WithMany("EventosCriados")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriarGrupo.Models.Grupo", "Grupo")
                        .WithMany("Eventos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("CriarGrupo.Models.Grupo", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SportConnect.Models.Usuario", b =>
                {
                    b.Navigation("EventosCriados");

                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
